services:
  db:
    image: mariadb

    container_name: mariadb
    
    environment:
      MARIADB_ROOT_PASSWORD: 123

    volumes:
      - mariadb_volume:/var/lib/mysql

    networks:
      - mariadb_network
    
    ports:
      - 3307:3306

volumes:
  mariadb_volume:

networks:
  mariadb_network:
