services:
  db:
    image: postgres:17.5-alpine
    restart: always
    shm_size: 128mb
    
    container_name: postgres
    
    environment:
      POSTGRES_DB: ${DB}
      POSTGRES_HOST: ${DB_HOST:-localhost}
      POSTGRES_USER: ${DB_USER:-admin}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    volumes:
      - postgres_volume:/var/lib/postgresql/data

    ports:
      - 5432:5432

    networks:
        - dbnet

  db_test:
    image: postgres:17.5-alpine
    restart: always
    shm_size: 128mb

    container_name: testDB

    environment:
      POSTGRES_DB: testDB
      POSTGRES_HOST: localhost
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123 

    ports:
      - 5433:5432

    networks:
        - dbnet
 
  # api:
  #   depends_on: ["db"]
  #   image: node:23.9.0

  #   environment:
  #     DB_PASSWORD : "123"

  #     HOST: ${HOST:-localhost}
  #     PORT_SERVER: ${PORT_SERVER:-3000}

  #   ports:
  #     - ${PORT_SERVER:-3000}

volumes:
  postgres_volume:

networks:
  dbnet:
    driver: bridge
